version: '3.8'
services:
  postgres-task:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_service_db
    ports:
      - "5434:5432"  # مختلف عن User Service (5433)
    volumes:
      - postgres_task_data:/var/lib/postgresql/data

volumes:
  postgres_task_data: